version: '3.8'

services:
  app:
    image: composer:latest
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    networks:
      - laravel_network

  nuxt:
    image: node:18
    container_name: nuxt-app
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
